---

- name: Include install.yml file conditionally
  include_tasks: install.yml
  when: (install_node_exporter | bool)

- name: Include uninstall.yml file
  include_tasks: uninstall.yml
  when: not (install_node_exporter | bool)
