---

- name: Get service facts
  service_facts:

- name: Check if node-exporter is installed
  set_fact:
    node_exporter_installed: true
  when: ansible_facts.services["node-exporter.service"] is defined

- name: Remove node-exporter
  block:
    - name: Ensure node-exporter service stopped and disabled
      service:
        name: node-exporter
        state: stopped
        enabled: false

    - name: Revoke firewalld permissions
      firewalld:
        port: "{{ exporter_port }}/tcp"
        immediate: true
        permanent: true
        state: disabled
      when: ansible_facts.services["firewalld.service"].state == "running"

    - name: Remove node-exporter related files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/node_exporter
        - /etc/systemd/system/node-exporter.service
        - "{{ folder_path }}"
      notify: force systemd to reread configs

    - name: Ensure {{ user }} user no more exists
      user:
        name: "{{ user }}"
        state: absent

    - name: Set fact after uninstallation
      set_fact:
        node_exporter_installed: false
  when: ansible_facts.services["node-exporter.service"] is defined
