---

- name: start and enable node-exporter
  systemd:
    name: node-exporter
    state: started
    enabled: true
    daemon_reload: true

- name: force systemd to reread configs
  systemd:
    daemon_reload: true

...
